---
# tasks file for coldfusion
- name: Install prerequisites
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - unzip
    - libfontconfig1

- name: Download ColdFusion installer
  get_url:
    url: "https://download.macromedia.com/pub/coldfusion/updates/14/apimanageraddoninstallers/ColdFusion_2021_APIManager_Addon_WWEJ_linux64.bin"
    dest: "/tmp/ColdFusion_2021_APIManager_Addon_WWEJ_linux64.bin"
    mode: '0755'

- name: Run ColdFusion installer
  command: "/tmp/ColdFusion_2021_APIManager_Addon_WWEJ_linux64.bin -f installer.profile"
  args:
    creates: "/opt/coldfusion2021"
