---
# tasks file for coldfusion
- name: Install prerequisites
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - unzip
    - libfontconfig1

- name: Download ColdFusion installer
  get_url:
    url: "https://download.adobe.com/pub/adobe/coldfusion/2021/Adobe_ColdFusion_2021_WWEJ_linux64.bin"
    dest: "/tmp/cf2021_installer.bin"
    mode: '0755'

- name: Run ColdFusion installer
  command: "/tmp/cf2021_installer.bin -f installer.profile"
  args:
    creates: "/opt/coldfusion2021"
